ARG NODE_BUILD_IMAGE=node:16.20.1-bullseye
FROM $NODE_BUILD_IMAGE AS build

WORKDIR /mongodb-client-encryption
COPY . .

RUN npm run install:libmongocrypt
RUN npm run test

FROM scratch

COPY --from=build /mongodb-client-encryption/prebuilds/ /
